export const BOOKS = [
  {
    Nr: '1',
    Emërtimi: 'Brenga e Ballkanit',
    Autori: 'Edith Durham',
    VitiIBotimit: '2009',
    ShtëpiaBotuese: 'Argeta LMG',
  },
  {
    Nr: '2',
    Emërtimi: 'Lirika',
    Autori: 'Hiqmet Mehmetaj',
    VitiIBotimit: '2014',
    ShtëpiaBotuese: 'Dudaj',
  },
  {
    Nr: '3',
    Emërtimi: 'Vepra 1,2,3 ',
    Autori: 'Ismail Kadare',
    VitiIBotimit: '2008',
    ShtëpiaBotuese: 'Onufri',
  },
  {
    Nr: '4',
    Emërtimi: 'Kërkime për shqiptarët',
    Autori: 'William Martin - Leake',
    VitiIBotimit: '2006',
    ShtëpiaBotuese: 'Bota Shqiptare',
  },
  {
    Nr: '5',
    Emërtimi: 'Çështja shqiptare',
    Autori: 'Anselmo Lorekio',
    VitiIBotimit: '2021',
    ShtëpiaBotuese: 'Reklama',
  },
  {
    Nr: '6',
    Emërtimi: 'Misioni amerikan në Shqipëri',
    Autori: 'Peter Lucas',
    VitiIBotimit: '2008',
    ShtëpiaBotuese: 'Bota Shqiptare',
  },
  {
    Nr: '7',
    Emërtimi: 'Fjalor pamor tregjuhësh',
    Autori: 'Jean-Claude Corbeil',
    VitiIBotimit: '2007',
    ShtëpiaBotuese: 'Edualba',
  },
  {
    Nr: '8',
    Emërtimi: 'Hyrje ne psikoanalizë 1',
    Autori: 'Sigmund Freud',
    VitiIBotimit: '2006',
    ShtëpiaBotuese: 'Fan Noli',
  },
  {
    Nr: '9',
    Emërtimi: 'Hyrje ne psikoanalizë 2',
    Autori: 'Sigmund Freud',
    VitiIBotimit: '2004',
    ShtëpiaBotuese: 'Fan Noli',
  },
  {
    Nr: '10',
    Emërtimi: 'Hyrje ne psikoanalizë 3',
    Autori: 'Sigmund Freud',
    VitiIBotimit: '2009',
    ShtëpiaBotuese: 'Fan Noli',
  },
  {
    Nr: '11',
    Emërtimi: 'Qyteti',
    Autori: 'Max Weber',
    VitiIBotimit: '2008',
    ShtëpiaBotuese: 'Fan Noli',
  },
  {
    Nr: '12',
    Emërtimi: 'Kështu foli Zarathustra',
    Autori: 'Friedrich Nietzsche',
    VitiIBotimit: '2018',
    ShtëpiaBotuese: 'Pema',
  },
  {
    Nr: '13',
    Emërtimi: 'Mendimi kritik Ietrar',
    Autori: 'Ndriҫim Kulla',
    VitiIBotimit: '2004',
    ShtëpiaBotuese: 'Plejad',
  },
  {
    Nr: '14',
    Emërtimi: 'Probleme shqiptare',
    Autori: 'Mehdi Frashëri',
    VitiIBotimit: '2006',
    ShtëpiaBotuese: 'Plejad',
  },
  {
    Nr: '15',
    Emërtimi: 'Meditime',
    Autori: 'Marcus Aurelius',
    VitiIBotimit: '2021',
    ShtëpiaBotuese: 'Minerva ose Pema',
  },
  {
    Nr: '16',
    Emërtimi: 'Mbi edukimin estetik',
    Autori: 'Friedrich Schiller',
    VitiIBotimit: '2004',
    ShtëpiaBotuese: 'Plejad',
  },
  {
    Nr: '17',
    Emërtimi: 'Paris 1919',
    Autori: 'Margaret Macmillan',
    VitiIBotimit: '2006',
    ShtëpiaBotuese: 'Plejad',
  },
  {
    Nr: '18',
    Emërtimi: 'Mbi njeriun',
    Autori: "Thoma D'Akuini",
    VitiIBotimit: '2005',
    ShtëpiaBotuese: 'Plejad',
  },
  {
    Nr: '19',
    Emërtimi: 'Vepra B.Merxhanit',
    Autori: 'Brancko Merxhani',
    VitiIBotimit: '2003',
    ShtëpiaBotuese: 'Plejad',
  },
  {
    Nr: '20',
    Emërtimi: 'Elita Shqiptare',
    Autori: 'Mithat Frashwri',
    VitiIBotimit: '2008',
    ShtëpiaBotuese: 'Plejad',
  },
  {
    Nr: '21',
    Emërtimi: 'Udhëtim në Ballkan',
    Autori: 'Guillaume Lejeani',
    VitiIBotimit: '2017',
    ShtëpiaBotuese: 'Dituria',
  },
  {
    Nr: '22',
    Emërtimi: 'Rrëfimet',
    Autori: 'Jean-Jacques Rousseau',
    VitiIBotimit: '2018',
    ShtëpiaBotuese: 'Pika pa sipwrfaqe',
  },
  {
    Nr: '23',
    Emërtimi: 'Politika si profesion',
    Autori: 'Max Weber',
    VitiIBotimit: '2009',
    ShtëpiaBotuese: 'Asdreni',
  },
  {
    Nr: '24',
    Emërtimi: 'Oriental apo okcidental',
    Autori: 'Krist Maloki',
    VitiIBotimit: '2003',
    ShtëpiaBotuese: 'Plejad',
  },
  {
    Nr: '25',
    Emërtimi: 'Misioni i shekullit XX',
    Autori: 'Tajar Zavalani',
    VitiIBotimit: '2010',
    ShtëpiaBotuese: 'Plejad',
  },
  {
    Nr: '26',
    Emërtimi: 'Dialogjet',
    Autori: 'Seneca',
    VitiIBotimit: '2004',
    ShtëpiaBotuese: 'Plejad',
  },
  {
    Nr: '27',
    Emërtimi: 'Lufta e Kosoves',
    Autori: 'Carlo Scognamiglio Pasini',
    VitiIBotimit: '2004',
    ShtëpiaBotuese: 'Geer',
  },
  {
    Nr: '28',
    Emërtimi: 'Në Kështjellë',
    Autori: 'Marianne Gruber',
    VitiIBotimit: '2007',
    ShtëpiaBotuese: 'Botimet 55',
  },
  {
    Nr: '29',
    Emërtimi: 'Sarkozi Pranvera e Francës',
    Autori: 'Catherine Nay',
    VitiIBotimit: '2009',
    ShtëpiaBotuese: 'Botimet 55',
  },
  {
    Nr: '30',
    Emërtimi: 'Histori Sekrete',
    Autori: 'Joel Levy',
    VitiIBotimit: '2007',
    ShtëpiaBotuese: 'Botimet 55',
  },
  {
    Nr: '31',
    Emërtimi: 'Lufta në Shqipëri',
    Autori: 'Gian Carlo Fusco',
    VitiIBotimit: '2008',
    ShtëpiaBotuese: 'Botimet 55',
  },
  {
    Nr: '32',
    Emërtimi: 'Rrno vetëm për me tregue',
    Autori: 'Zef Pllumi',
    VitiIBotimit: '2006',
    ShtëpiaBotuese: 'Botimet 55',
  },
  {
    Nr: '33',
    Emërtimi: 'Ibrahim Rrugova',
    Autori: 'Gjon Keka',
    VitiIBotimit: '2011',
    ShtëpiaBotuese: 'Botart',
  },
  {
    Nr: '34',
    Emërtimi: 'Fytyra e Vërtetë e Haxhi Qamilit',
    Autori: 'Thanas Floqi',
    VitiIBotimit: '2008',
    ShtëpiaBotuese: 'Botimet 55',
  },
  {
    Nr: '35',
    Emërtimi: 'Vajza e Agamemnonit',
    Autori: 'Ismail Kadare',
    VitiIBotimit: '2003',
    ShtëpiaBotuese: 'Botimet 55',
  },
  {
    Nr: '36',
    Emërtimi: 'Arkitekti',
    Autori: 'Fahri Balliu',
    VitiIBotimit: '2009',
    ShtëpiaBotuese: 'Botimet 55',
  },
  {
    Nr: '37',
    Emërtimi: 'Panteoni i Zi',
    Autori: 'Fahri Balliu',
    VitiIBotimit: '2007',
    ShtëpiaBotuese: 'Botimet 55',
  },
  {
    Nr: '38',
    Emërtimi: 'Zonja e Zezë Nexhmije Hoxha',
    Autori: 'Fahri Balliu',
    VitiIBotimit: '2010',
    ShtëpiaBotuese: 'Botimet 55',
  },
  {
    Nr: '39',
    Emërtimi: 'Rrwmbimi i Europws',
    Autori: 'Aurel Plasari',
    VitiIBotimit: '2005',
    ShtëpiaBotuese: 'Botimet 55',
  },
  {
    Nr: '40',
    Emërtimi: 'Berisha përmes Kasandrave',
    Autori: 'Fahri Balliu',
    VitiIBotimit: '2009',
    ShtëpiaBotuese: 'Botimet 55',
  },
  {
    Nr: '41',
    Emërtimi: 'Përralla nga e giithë bota',
    Autori: 'Grup autorësh',
    VitiIBotimit: '2009',
    ShtëpiaBotuese: 'Botimet 55',
  },
  {
    Nr: '42',
    Emërtimi: 'Histori kurrë e shkrueme',
    Autori: 'Zef Pllumi',
    VitiIBotimit: '2006',
    ShtëpiaBotuese: 'Botimet 55',
  },
  {
    Nr: '43',
    Emërtimi: 'Muret e Krujës',
    Autori: 'Gjergj Zheji',
    VitiIBotimit: '2009',
    ShtëpiaBotuese: 'Botimet 55',
  },
  {
    Nr: '44',
    Emërtimi: 'Masakër në Camëri',
    Autori: 'Kastriot Dervishi',
    VitiIBotimit: '2009',
    ShtëpiaBotuese: 'Botimet 55',
  },
  {
    Nr: '45',
    Emërtimi: 'Mehmeti pushtuesi i parë',
    Autori: 'Franc Babinger',
    VitiIBotimit: '2005',
    ShtëpiaBotuese: 'Botimet 55',
  },
  {
    Nr: '46',
    Emërtimi: 'Mehmeti pushtuesi i dytë',
    Autori: 'Franc Babinger',
    VitiIBotimit: '2005',
    ShtëpiaBotuese: 'Botimet 55',
  },
  {
    Nr: '47',
    Emërtimi: 'Shqiptarët në Venedik',
    Autori: 'Lucia Nadin',
    VitiIBotimit: '2008',
    ShtëpiaBotuese: 'Botimet 55',
  },
  {
    Nr: '48',
    Emërtimi: 'Dashuria për jetën',
    Autori: 'Erich Fromm',
    VitiIBotimit: '2006',
    ShtëpiaBotuese: 'Botimet 55',
  },
  {
    Nr: '49',
    Emërtimi: 'Luftrat Ballkanike',
    Autori: 'Egidio Ivetic',
    VitiIBotimit: '2008',
    ShtëpiaBotuese: 'Dituria',
  },
  {
    Nr: '50',
    Emërtimi: 'Princi',
    Autori: 'Niccolò Machiavelli',
    VitiIBotimit: '2017',
    ShtëpiaBotuese: 'Botime Pema',
  },
  {
    Nr: '51',
    Emërtimi: 'Rraca Shqiptare',
    Autori: 'Jakov Milaj',
    VitiIBotimit: '1994',
    ShtëpiaBotuese: 'Ismail Mal Osmani',
  },
  {
    Nr: '52',
    Emërtimi: 'Aforizma',
    Autori: 'Ermal Qori',
    VitiIBotimit: '2016',
    ShtëpiaBotuese: 'Jonalda',
  },
  {
    Nr: '53',
    Emërtimi: 'Bizanti',
    Autori: 'John Julius Norwich',
    VitiIBotimit: '2005',
    ShtëpiaBotuese: 'Uegen',
  },
  {
    Nr: '54',
    Emërtimi: 'Ballkani',
    Autori: 'Mark Mazower',
    VitiIBotimit: '2010',
    ShtëpiaBotuese: 'Skanderbeg Books',
  },
  {
    Nr: '55',
    Emërtimi: 'Shqipëria vend i Shqiptarëve',
    Autori: 'Hugo A. Bernatzik',
    VitiIBotimit: '2003',
    ShtëpiaBotuese: 'Uegen',
  },
  {
    Nr: '56',
    Emërtimi: 'Ecce Homo',
    Autori: 'Friedrich Nietzsche',
    VitiIBotimit: '2005',
    ShtëpiaBotuese: 'Uegen',
  },
  {
    Nr: '57',
    Emërtimi: 'Fjalor sinonimesh',
    Autori: 'Edmond Tupe, Eshref Ymeri, Ali Dhrimo',
    VitiIBotimit: '2007',
    ShtëpiaBotuese: 'EDFA',
  },
  {
    Nr: '58',
    Emërtimi: 'Historia Botërore 1-12',
    Autori: 'Carl Grimberg',
    VitiIBotimit: '2005',
    ShtëpiaBotuese: 'Uegen',
  },
  {
    Nr: '59',
    Emërtimi: 'Mrizi i Zanave',
    Autori: 'Gjergj Fishta',
    VitiIBotimit: '2010',
    ShtëpiaBotuese: 'Reklama',
  },
  {
    Nr: '60',
    Emërtimi: 'Doktorr gjilpëra',
    Autori: 'Faik Konica',
    VitiIBotimit: '2011',
    ShtëpiaBotuese: 'West Print',
  },
  {
    Nr: '61',
    Emërtimi: 'Zhvillimi të menduarit 6-12',
    Autori: 'JEFF ZWIERS',
    VitiIBotimit: '2005',
    ShtëpiaBotuese: 'Cde',
  },
  {
    Nr: '62',
    Emërtimi: 'Historia e Ballkanit',
    Autori: 'Georges Castellan',
    VitiIBotimit: '1991',
    ShtëpiaBotuese: 'Çabej',
  },
  {
    Nr: '63',
    Emërtimi: 'Lufta Civile Shqipëri 43-45',
    Autori: 'Uran Butka',
    VitiIBotimit: '2015',
    ShtëpiaBotuese: 'Iskpk',
  },
  {
    Nr: '64',
    Emërtimi: 'Dialog me Alen Boske',
    Autori: 'Ismail Kadare',
    VitiIBotimit: '2002',
    ShtëpiaBotuese: 'Onufri',
  },
  {
    Nr: '65',
    Emërtimi: 'Ikja e Shtegut',
    Autori: 'Ismail Kadare',
    VitiIBotimit: '2003',
    ShtëpiaBotuese: 'Onufri',
  },
  {
    Nr: '66',
    Emërtimi: 'Kushëriri i engjëjve',
    Autori: 'Ismail Kadare',
    VitiIBotimit: '2005',
    ShtëpiaBotuese: 'Onufri',
  },
  {
    Nr: '67',
    Emërtimi: 'Vjedhja e gjumit mbretëror',
    Autori: 'Ismail Kadare',
    VitiIBotimit: '2012',
    ShtëpiaBotuese: 'Onufri',
  },
  {
    Nr: '68',
    Emërtimi: 'Kronikë në gur',
    Autori: 'Ismail Kadare',
    VitiIBotimit: '2000',
    ShtëpiaBotuese: 'Onufri',
  },
  {
    Nr: '69',
    Emërtimi: 'Eskili ky humbës i madh',
    Autori: 'Ismail Kadare',
    VitiIBotimit: '2015',
    ShtëpiaBotuese: 'Onufri',
  },
  {
    Nr: '70',
    Emërtimi: 'Bisedë permes hekurave',
    Autori: 'Ismail Kadare',
    VitiIBotimit: '2014',
    ShtëpiaBotuese: ' Onufri',
  },
  {
    Nr: '71',
    Emërtimi: 'Hamleti',
    Autori: 'William Shakespeare',
    VitiIBotimit: '2005',
    ShtëpiaBotuese: 'Onufri',
  },
  {
    Nr: '72',
    Emërtimi: 'Jul Qezari',
    Autori: 'William Shakespeare',
    VitiIBotimit: '2005',
    ShtëpiaBotuese: 'Onufri',
  },
  {
    Nr: '73',
    Emërtimi: 'Otello',
    Autori: 'William Shakespeare',
    VitiIBotimit: '2005',
    ShtëpiaBotuese: 'Argeta LMG',
  },
  {
    Nr: '74',
    Emërtimi: 'Ëndrra e një nate vere',
    Autori: 'William Shakespeare',
    VitiIBotimit: '2007',
    ShtëpiaBotuese: 'Onufri',
  },
  {
    Nr: '75',
    Emërtimi: 'Rubairat',
    Autori: 'Omar Khayyam',
    VitiIBotimit: '2007',
    ShtëpiaBotuese: 'Onufri',
  },
  {
    Nr: '76',
    Emërtimi: 'Shën Maria e Parisit',
    Autori: 'Viktor Hygo',
    VitiIBotimit: '2002',
    ShtëpiaBotuese: 'Uegen',
  },
  {
    Nr: '77',
    Emërtimi: 'Idioti',
    Autori: 'Fyodor Dostoevsky',
    VitiIBotimit: '2000',
    ShtëpiaBotuese: 'Uegen',
  },
  {
    Nr: '78',
    Emërtimi: 'Adoleshenti',
    Autori: 'Fyodor Dostoevsky',
    VitiIBotimit: '2000',
    ShtëpiaBotuese: 'Uegen',
  },
  {
    Nr: '79',
    Emërtimi: 'Lahuta e Malcisë',
    Autori: 'Gjergj Fishta',
    VitiIBotimit: '2013',
    ShtëpiaBotuese: 'Botime Françeskane',
  },
  {
    Nr: '80',
    Emërtimi: 'Vepra Letrare',
    Autori: 'Ndre Mjeda',
    VitiIBotimit: '2012',
    ShtëpiaBotuese: 'Uegen',
  },
  {
    Nr: '81',
    Emërtimi: 'Vepra Letrare',
    Autori: 'A. Z. Çajupi',
    VitiIBotimit: '2020',
    ShtëpiaBotuese: 'Uegen',
  },
  {
    Nr: '82',
    Emërtimi: 'Tre shokët',
    Autori: 'Erih Maria Remark',
    VitiIBotimit: '2001',
    ShtëpiaBotuese: 'Dituria',
  },
  {
    Nr: '83',
    Emërtimi: 'Qielli ska preferenca',
    Autori: 'Erih Maria Remark',
    VitiIBotimit: '2001',
    ShtëpiaBotuese: 'Uegen',
  },
  {
    Nr: '84',
    Emërtimi: 'Ana zh',
    Autori: 'Nasi Lera',
    VitiIBotimit: '1995',
    ShtëpiaBotuese: 'Onufri',
  },
  {
    Nr: '85',
    Emërtimi: 'Haxhi murati',
    Autori: 'Lev Tolstoj',
    VitiIBotimit: '2016',
    ShtëpiaBotuese: 'Onufri',
  },
  {
    Nr: '86',
    Emërtimi: 'Të kesh dhe të mos kesh',
    Autori: 'Ernest Hemingway',
    VitiIBotimit: '2007',
    ShtëpiaBotuese: 'Onufri',
  },
  {
    Nr: '87',
    Emërtimi: 'Tarsa bubla',
    Autori: 'Nikolai Gogol',
    VitiIBotimit: '2006',
    ShtëpiaBotuese: 'Ombra GVG',
  },
  {
    Nr: '88',
    Emërtimi: 'Autobiografia e popullit ne vargje',
    Autori: 'Ismail Kadare',
    VitiIBotimit: '2002',
    ShtëpiaBotuese: 'Onufri',
  },
  {
    Nr: '89',
    Emërtimi: 'Gjenerali i Ushrisë së vdekur',
    Autori: 'Ismail Kadare',
    VitiIBotimit: '2015',
    ShtëpiaBotuese: 'Onufri',
  },
  {
    Nr: '90',
    Emërtimi: 'Kështjella',
    Autori: 'Ismail Kadare',
    VitiIBotimit: '2015',
    ShtëpiaBotuese: 'Onufri',
  },
  {
    Nr: '91',
    Emërtimi: 'Viti i mbrapshtë',
    Autori: 'Ismail Kadare',
    VitiIBotimit: '2003',
    ShtëpiaBotuese: 'Onufri',
  },
  {
    Nr: '92',
    Emërtimi: 'Poezi ca pika shiu',
    Autori: 'Ismail Kadare',
    VitiIBotimit: '2003',
    ShtëpiaBotuese: 'Onufri',
  },
  {
    Nr: '93',
    Emërtimi: 'Kush e solli Doruntinën',
    Autori: 'Ismail Kadare',
    VitiIBotimit: '2004',
    ShtëpiaBotuese: 'Onufri',
  },
  {
    Nr: '94',
    Emërtimi: 'Nata me Hënë',
    Autori: 'Ismail Kadare',
    VitiIBotimit: '2009',
    ShtëpiaBotuese: 'Onufri',
  },
  {
    Nr: '95',
    Emërtimi: 'Hamleti Princi i Vështirë',
    Autori: 'Ismail Kadare',
    VitiIBotimit: '2014',
    ShtëpiaBotuese: 'Onufri',
  },
  {
    Nr: '96',
    Emërtimi: 'Ura me tre harqe',
    Autori: 'Ismail Kadare',
    VitiIBotimit: '2015',
    ShtëpiaBotuese: 'Onufri',
  },
];
